%-----------------------------------------------------------------------
% Job saved on 04-Dec-2024 17:14:57 by cfg_util (rev $Rev: 7345 $)
% spm SPM - SPM12 (7771)
% cfg_basicio BasicIO - Unknown
%-----------------------------------------------------------------------
matlabbatch{1}.spm.stats.factorial_design.dir = '<UNDEFINED>';
matlabbatch{1}.spm.stats.factorial_design.des.t1.scans = '<UNDEFINED>';
%%
matlabbatch{1}.spm.stats.factorial_design.cov(1).c = [73
                                                      25
                                                      74
                                                      22
                                                      66
                                                      22
                                                      64
                                                      68
                                                      67
                                                      24
                                                      64
                                                      22
                                                      66
                                                      20
                                                      64
                                                      71
                                                      65
                                                      32
                                                      69
                                                      59
                                                      21
                                                      68
                                                      43
                                                      72
                                                      72
                                                      65
                                                      46
                                                      71
                                                      26
                                                      73
                                                      28
                                                      71
                                                      20
                                                      20
                                                      30
                                                      19
                                                      28
                                                      25
                                                      27
                                                      72
                                                      70
                                                      20
                                                      30
                                                      65
                                                      26
                                                      74
                                                      47
                                                      29
                                                      19
                                                      20
                                                      29
                                                      68
                                                      65
                                                      22
                                                      73
                                                      27
                                                      31
                                                      71
                                                      23
                                                      20
                                                      50
                                                      69
                                                      64
                                                      21
                                                      54
                                                      65
                                                      34
                                                      43
                                                      27
                                                      22
                                                      21
                                                      58
                                                      21
                                                      58
                                                      64
                                                      71
                                                      19
                                                      75
                                                      29
                                                      24
                                                      27
                                                      21
                                                      74
                                                      59
                                                      60
                                                      67
                                                      64
                                                      20
                                                      26
                                                      20
                                                      64
                                                      70
                                                      33
                                                      23
                                                      27
                                                      22
                                                      55
                                                      32
                                                      22
                                                      74
                                                      42
                                                      69
                                                      25
                                                      27
                                                      26
                                                      62
                                                      26
                                                      68
                                                      62
                                                      72
                                                      26
                                                      65
                                                      62
                                                      26
                                                      72
                                                      54
                                                      24
                                                      64
                                                      75
                                                      50
                                                      30
                                                      66
                                                      68
                                                      70
                                                      64
                                                      68
                                                      25
                                                      60
                                                      52
                                                      71
                                                      62
                                                      71
                                                      19
                                                      23
                                                      60
                                                      30
                                                      68
                                                      20];
%%
matlabbatch{1}.spm.stats.factorial_design.cov(1).cname = 'Age';
matlabbatch{1}.spm.stats.factorial_design.cov(1).iCFI = 1;
matlabbatch{1}.spm.stats.factorial_design.cov(1).iCC = 1;
%%
matlabbatch{1}.spm.stats.factorial_design.cov(2).c = [0
                                                      0
                                                      1
                                                      0
                                                      1
                                                      1
                                                      0
                                                      1
                                                      0
                                                      1
                                                      0
                                                      0
                                                      0
                                                      0
                                                      1
                                                      0
                                                      1
                                                      1
                                                      0
                                                      0
                                                      1
                                                      0
                                                      1
                                                      1
                                                      0
                                                      0
                                                      1
                                                      1
                                                      0
                                                      0
                                                      1
                                                      0
                                                      0
                                                      1
                                                      0
                                                      0
                                                      0
                                                      0
                                                      0
                                                      0
                                                      1
                                                      0
                                                      0
                                                      1
                                                      1
                                                      0
                                                      0
                                                      1
                                                      0
                                                      1
                                                      1
                                                      1
                                                      0
                                                      1
                                                      0
                                                      0
                                                      0
                                                      0
                                                      0
                                                      0
                                                      0
                                                      1
                                                      0
                                                      1
                                                      1
                                                      0
                                                      1
                                                      0
                                                      0
                                                      0
                                                      0
                                                      0
                                                      0
                                                      0
                                                      0
                                                      0
                                                      1
                                                      0
                                                      0
                                                      0
                                                      1
                                                      0
                                                      1
                                                      1
                                                      0
                                                      1
                                                      0
                                                      0
                                                      0
                                                      1
                                                      1
                                                      0
                                                      0
                                                      0
                                                      0
                                                      0
                                                      1
                                                      0
                                                      0
                                                      0
                                                      1
                                                      1
                                                      0
                                                      0
                                                      0
                                                      0
                                                      0
                                                      1
                                                      0
                                                      0
                                                      1
                                                      1
                                                      0
                                                      0
                                                      0
                                                      0
                                                      0
                                                      1
                                                      0
                                                      0
                                                      0
                                                      1
                                                      0
                                                      1
                                                      0
                                                      1
                                                      0
                                                      1
                                                      0
                                                      1
                                                      0
                                                      0
                                                      0
                                                      1
                                                      0
                                                      1
                                                      1
                                                      0];
%%
matlabbatch{1}.spm.stats.factorial_design.cov(2).cname = 'Sex';
matlabbatch{1}.spm.stats.factorial_design.cov(2).iCFI = 1;
matlabbatch{1}.spm.stats.factorial_design.cov(2).iCC = 1;
%%
matlabbatch{1}.spm.stats.factorial_design.cov(3).c = [1.5481049974357
                                                      1.53698514971926
                                                      1.80899465208014
                                                      1.54358448736444
                                                      1.82033264490752
                                                      1.53536674570198
                                                      1.60634152636995
                                                      1.5008047083639
                                                      1.55991341382032
                                                      1.75423472727306
                                                      1.6589030392823
                                                      1.64074606958107
                                                      1.4809835699368
                                                      1.38216573272026
                                                      1.97533377172119
                                                      1.48244223668973
                                                      1.86085035710762
                                                      2.12813851409124
                                                      1.58580763888109
                                                      1.47713434617975
                                                      1.80805113045571
                                                      1.61064549525193
                                                      1.68111174255649
                                                      1.79633332191959
                                                      1.53516502019986
                                                      1.63829937531873
                                                      1.58856427433823
                                                      1.64292339127846
                                                      1.63863128122071
                                                      1.62463581764793
                                                      1.7953653022545
                                                      1.67719527957977
                                                      1.71220319929717
                                                      1.74446993061715
                                                      1.64606904244488
                                                      1.6335132220945
                                                      1.55364640560655
                                                      1.52464166271477
                                                      1.61006876580606
                                                      1.52364956069532
                                                      1.81806575457738
                                                      1.48441434661028
                                                      1.74591876991852
                                                      1.74245769520403
                                                      1.68360241721359
                                                      1.4747350401555
                                                      1.70820300690374
                                                      1.63520753984176
                                                      1.54707773070829
                                                      1.71483693670782
                                                      1.82063798610205
                                                      1.5423047696417
                                                      1.36841720641699
                                                      1.51911707023119
                                                      1.47224669491031
                                                      1.53270736907412
                                                      1.44092665776395
                                                      1.47874040901983
                                                      1.67742379724035
                                                      1.43908967726316
                                                      1.52853442765087
                                                      1.61883444867739
                                                      1.68423088391742
                                                      1.85153421930177
                                                      1.50277601436284
                                                      1.64343643836763
                                                      1.74377382077206
                                                      1.44132471268945
                                                      1.57237295573363
                                                      1.54282540888818
                                                      1.57267292437882
                                                      1.4827121857253
                                                      1.48834749194092
                                                      1.32874117661961
                                                      1.44092265776372
                                                      1.79406395315794
                                                      1.70605483814925
                                                      1.43495109662625
                                                      1.34450296578704
                                                      1.47328963222689
                                                      1.79688902783481
                                                      1.57649271676158
                                                      1.79057300001031
                                                      1.88918360584204
                                                      1.52302356457986
                                                      1.99562837292139
                                                      1.52942978456656
                                                      1.67107434196289
                                                      1.53620160457489
                                                      1.96631283785436
                                                      1.74790551905562
                                                      1.65931321577715
                                                      1.6700851654338
                                                      1.44785213268332
                                                      1.65398198801089
                                                      1.52130782330193
                                                      1.48237518570537
                                                      1.45366110557588
                                                      1.59160994902815
                                                      1.54994974264284
                                                      1.50311290457884
                                                      1.43265122982357
                                                      1.43109855914351
                                                      1.52379030972325
                                                      1.55404846445386
                                                      1.59099746663899
                                                      1.63541875554053
                                                      1.67845939730159
                                                      1.4683705417399
                                                      1.44954205043032
                                                      1.59167416471822
                                                      1.80966225604119
                                                      1.76346468860323
                                                      1.74419352667924
                                                      1.56492868470515
                                                      1.64671935228726
                                                      1.83481766537199
                                                      1.66938616931403
                                                      1.47482282055285
                                                      1.52127237624101
                                                      1.56173245314358
                                                      1.61432932292077
                                                      1.37890279135083
                                                      1.74127843631076
                                                      1.54790613467884
                                                      1.71058477175047
                                                      1.61395508760452
                                                      1.66214826300364
                                                      1.52823253743694
                                                      1.83420569670835
                                                      1.42706451184612
                                                      1.60311405166927
                                                      1.57826514431738
                                                      1.88651406058613
                                                      1.39753158068781
                                                      1.68681273112893
                                                      1.55211166826089
                                                      1.50029184166691];
%%
matlabbatch{1}.spm.stats.factorial_design.cov(3).cname = 'TIV';
matlabbatch{1}.spm.stats.factorial_design.cov(3).iCFI = 1;
matlabbatch{1}.spm.stats.factorial_design.cov(3).iCC = 1;
%%
matlabbatch{1}.spm.stats.factorial_design.cov(4).c = [1
                                                      1
                                                      0
                                                      0
                                                      1
                                                      0
                                                      0
                                                      1
                                                      1
                                                      1
                                                      1
                                                      0
                                                      1
                                                      0
                                                      1
                                                      1
                                                      1
                                                      0
                                                      1
                                                      0
                                                      1
                                                      1
                                                      0
                                                      1
                                                      1
                                                      1
                                                      0
                                                      0
                                                      0
                                                      1
                                                      0
                                                      1
                                                      1
                                                      1
                                                      1
                                                      0
                                                      0
                                                      0
                                                      1
                                                      1
                                                      1
                                                      1
                                                      1
                                                      1
                                                      0
                                                      1
                                                      0
                                                      0
                                                      1
                                                      1
                                                      0
                                                      1
                                                      1
                                                      1
                                                      0
                                                      0
                                                      0
                                                      1
                                                      0
                                                      1
                                                      0
                                                      1
                                                      0
                                                      1
                                                      0
                                                      1
                                                      0
                                                      0
                                                      1
                                                      1
                                                      1
                                                      0
                                                      0
                                                      0
                                                      0
                                                      1
                                                      1
                                                      1
                                                      0
                                                      0
                                                      0
                                                      1
                                                      1
                                                      0
                                                      0
                                                      0
                                                      1
                                                      1
                                                      1
                                                      1
                                                      0
                                                      1
                                                      0
                                                      1
                                                      0
                                                      1
                                                      0
                                                      0
                                                      0
                                                      1
                                                      0
                                                      1
                                                      0
                                                      0
                                                      0
                                                      0
                                                      1
                                                      1
                                                      0
                                                      1
                                                      1
                                                      0
                                                      0
                                                      0
                                                      1
                                                      0
                                                      0
                                                      1
                                                      1
                                                      0
                                                      1
                                                      0
                                                      1
                                                      1
                                                      1
                                                      1
                                                      0
                                                      0
                                                      0
                                                      0
                                                      0
                                                      0
                                                      1
                                                      0
                                                      0
                                                      0
                                                      0
                                                      0];
matlabbatch{1}.spm.stats.factorial_design.cov(4).cname = 'Scanner';
matlabbatch{1}.spm.stats.factorial_design.cov(4).iCFI = 1;
matlabbatch{1}.spm.stats.factorial_design.cov(4).iCC = 1;
matlabbatch{1}.spm.stats.factorial_design.multi_cov = struct('files', {}, 'iCFI', {}, 'iCC', {});
matlabbatch{1}.spm.stats.factorial_design.masking.tm.tm_none = 1;
matlabbatch{1}.spm.stats.factorial_design.masking.im = 0;
matlabbatch{1}.spm.stats.factorial_design.masking.em = {''};
matlabbatch{1}.spm.stats.factorial_design.globalc.g_omit = 1;
matlabbatch{1}.spm.stats.factorial_design.globalm.gmsca.gmsca_no = 1;
matlabbatch{1}.spm.stats.factorial_design.globalm.glonorm = 1;
%%
matlabbatch{2}.spm.stats.fmri_est.spmmat(1) = cfg_dep('Factorial design specification: SPM.mat File', substruct('.','val', '{}',{1}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','spmmat'));
matlabbatch{2}.spm.stats.fmri_est.write_residuals = 0;
matlabbatch{2}.spm.stats.fmri_est.method.Classical = 1;
%%
matlabbatch{3}.spm.stats.con.spmmat(1) = cfg_dep('Model estimation: SPM.mat File', substruct('.','val', '{}',{2}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','spmmat'));
matlabbatch{3}.spm.stats.con.consess{1}.fcon.name = 'Global Effect of TWS-TSPOON Difference';
matlabbatch{3}.spm.stats.con.consess{1}.fcon.weights = [1 0 0 0 0];
matlabbatch{3}.spm.stats.con.consess{1}.fcon.sessrep = 'none';
matlabbatch{3}.spm.stats.con.consess{2}.fcon.name = 'Any_covariate';
matlabbatch{3}.spm.stats.con.consess{2}.fcon.weights = [0 1 0 0 0
                                                        0 0 1 0 0
                                                        0 0 0 1 0
                                                        0 0 0 0 1];
matlabbatch{3}.spm.stats.con.consess{2}.fcon.sessrep = 'none';
matlabbatch{3}.spm.stats.con.delete = 0;
