%-----------------------------------------------------------------------
% Job saved on 11-Mar-2026 14:29:59 by cfg_util (rev $Rev: 7345 $)
% spm SPM - SPM12 (7771)
% cfg_basicio BasicIO - Unknown
%-----------------------------------------------------------------------
matlabbatch{1}.spm.tools.snpm.des.Corr.DesignName = 'MultiSub: Simple Regression; 1 covariate of interest';
matlabbatch{1}.spm.tools.snpm.des.Corr.DesignFile = 'snpm_bch_ui_Corr';
matlabbatch{1}.spm.tools.snpm.des.Corr.dir = {'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\snpm_mreg-age'};
%%
matlabbatch{1}.spm.tools.snpm.des.Corr.P = {
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S001_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S002_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S003_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S004_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S005_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S006_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S007_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S008_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S009_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S010_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S011_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S012_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S013_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S014_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S015_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S016_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S017_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S018_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S019_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S020_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S021_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S022_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S023_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S024_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S025_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S026_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S027_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S028_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S029_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S030_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S031_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S032_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S033_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S034_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S035_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S036_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S037_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S038_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S039_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S040_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S041_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S042_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S043_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S044_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S045_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S046_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S047_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S048_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S049_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S050_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S051_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S052_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S053_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S054_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S055_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S056_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S057_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S058_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S059_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S060_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S061_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S062_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S063_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S064_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S065_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S066_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S067_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S068_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S069_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S070_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S071_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S072_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S073_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S074_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S075_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S076_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S077_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S078_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S079_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S080_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S081_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S082_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S083_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S084_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S085_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S086_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S087_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S088_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S089_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S090_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S091_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S092_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S093_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S094_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S095_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S096_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S097_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S098_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S099_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S100_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S101_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S102_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S103_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S104_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S105_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S106_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S107_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S108_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S109_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S110_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S111_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S112_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S113_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S114_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S115_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S116_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S117_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S118_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S119_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S120_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S121_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S122_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S123_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S124_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S125_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S126_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S127_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S128_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S129_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S130_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S131_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S132_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S133_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S134_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S135_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S136_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S137_space-MNI_R2starmap.nii,1'
                                            'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\AJ-SUSAN_unzipped\susan_Mask_GM_sub-S138_space-MNI_R2starmap.nii,1'
                                            };
%%
matlabbatch{1}.spm.tools.snpm.des.Corr.CovInt = [73 25 74 22 66 22 64 68 67 24 64 22 66 20 64 71 65 32 69 59 21 68 43 72 72 65 46 71 26 73 28 71 20 20 30 19 28 25 27 72 70 20 30 65 26 74 47 29 19 20 29 68 65 22 73 27 31 71 23 20 50 69 64 21 54 65 34 43 27 22 21 58 21 58 64 71 19 75 29 24 27 21 74 59 60 67 64 20 26 20 64 70 33 23 27 22 55 32 22 74 42 69 25 27 26 62 26 68 62 72 26 65 62 26 72 54 24 64 75 50 30 66 68 70 64 68 25 60 52 71 62 71 19 23 60 30 68 20];
%%
matlabbatch{1}.spm.tools.snpm.des.Corr.cov(1).c = [1
                                                   1
                                                   0
                                                   0
                                                   1
                                                   0
                                                   0
                                                   1
                                                   1
                                                   1
                                                   1
                                                   0
                                                   1
                                                   0
                                                   1
                                                   1
                                                   1
                                                   0
                                                   1
                                                   0
                                                   1
                                                   1
                                                   0
                                                   1
                                                   1
                                                   1
                                                   0
                                                   0
                                                   0
                                                   1
                                                   0
                                                   1
                                                   1
                                                   1
                                                   1
                                                   0
                                                   0
                                                   0
                                                   1
                                                   1
                                                   1
                                                   1
                                                   1
                                                   1
                                                   0
                                                   1
                                                   0
                                                   0
                                                   1
                                                   1
                                                   0
                                                   1
                                                   1
                                                   1
                                                   0
                                                   0
                                                   0
                                                   1
                                                   0
                                                   1
                                                   0
                                                   1
                                                   0
                                                   1
                                                   0
                                                   1
                                                   0
                                                   0
                                                   1
                                                   1
                                                   1
                                                   0
                                                   0
                                                   0
                                                   0
                                                   1
                                                   1
                                                   1
                                                   0
                                                   0
                                                   0
                                                   1
                                                   1
                                                   0
                                                   0
                                                   0
                                                   1
                                                   1
                                                   1
                                                   1
                                                   0
                                                   1
                                                   0
                                                   1
                                                   0
                                                   1
                                                   0
                                                   0
                                                   0
                                                   1
                                                   0
                                                   1
                                                   0
                                                   0
                                                   0
                                                   0
                                                   1
                                                   1
                                                   0
                                                   1
                                                   1
                                                   0
                                                   0
                                                   0
                                                   1
                                                   0
                                                   0
                                                   1
                                                   1
                                                   0
                                                   1
                                                   0
                                                   1
                                                   1
                                                   1
                                                   1
                                                   0
                                                   0
                                                   0
                                                   0
                                                   0
                                                   0
                                                   1
                                                   0
                                                   0
                                                   0
                                                   0
                                                   0];
%%
matlabbatch{1}.spm.tools.snpm.des.Corr.cov(1).cname = 'scanner';
%%
matlabbatch{1}.spm.tools.snpm.des.Corr.cov(2).c = [0
                                                   0
                                                   1
                                                   0
                                                   1
                                                   1
                                                   0
                                                   1
                                                   0
                                                   1
                                                   0
                                                   0
                                                   0
                                                   0
                                                   1
                                                   0
                                                   1
                                                   1
                                                   0
                                                   0
                                                   1
                                                   0
                                                   1
                                                   1
                                                   0
                                                   0
                                                   1
                                                   1
                                                   0
                                                   0
                                                   1
                                                   0
                                                   0
                                                   1
                                                   0
                                                   0
                                                   0
                                                   0
                                                   0
                                                   0
                                                   1
                                                   0
                                                   0
                                                   1
                                                   1
                                                   0
                                                   0
                                                   1
                                                   0
                                                   1
                                                   1
                                                   1
                                                   0
                                                   1
                                                   0
                                                   0
                                                   0
                                                   0
                                                   0
                                                   0
                                                   0
                                                   1
                                                   0
                                                   1
                                                   1
                                                   0
                                                   1
                                                   0
                                                   0
                                                   0
                                                   0
                                                   0
                                                   0
                                                   0
                                                   0
                                                   0
                                                   1
                                                   0
                                                   0
                                                   0
                                                   1
                                                   0
                                                   1
                                                   1
                                                   0
                                                   1
                                                   0
                                                   0
                                                   0
                                                   1
                                                   1
                                                   0
                                                   0
                                                   0
                                                   0
                                                   0
                                                   1
                                                   0
                                                   0
                                                   0
                                                   1
                                                   1
                                                   0
                                                   0
                                                   0
                                                   0
                                                   0
                                                   1
                                                   0
                                                   0
                                                   1
                                                   1
                                                   0
                                                   0
                                                   0
                                                   0
                                                   0
                                                   1
                                                   0
                                                   0
                                                   0
                                                   1
                                                   0
                                                   1
                                                   0
                                                   1
                                                   0
                                                   1
                                                   0
                                                   1
                                                   0
                                                   0
                                                   0
                                                   1
                                                   0
                                                   1
                                                   1
                                                   0];
%%
matlabbatch{1}.spm.tools.snpm.des.Corr.cov(2).cname = 'gender';
%%
matlabbatch{1}.spm.tools.snpm.des.Corr.cov(3).c = [1.5481049974357
                                                   1.53698514971926
                                                   1.80899465208014
                                                   1.54358448736444
                                                   1.82033264490752
                                                   1.53536674570198
                                                   1.60634152636995
                                                   1.5008047083639
                                                   1.55991341382032
                                                   1.75423472727306
                                                   1.6589030392823
                                                   1.64074606958107
                                                   1.4809835699368
                                                   1.38216573272026
                                                   1.97533377172119
                                                   1.48244223668973
                                                   1.86085035710762
                                                   2.12813851409124
                                                   1.58580763888109
                                                   1.47713434617975
                                                   1.80805113045571
                                                   1.61064549525193
                                                   1.68111174255649
                                                   1.79633332191959
                                                   1.53516502019986
                                                   1.63829937531873
                                                   1.58856427433823
                                                   1.64292339127846
                                                   1.63863128122071
                                                   1.62463581764793
                                                   1.7953653022545
                                                   1.67719527957977
                                                   1.71220319929717
                                                   1.74446993061715
                                                   1.64606904244488
                                                   1.6335132220945
                                                   1.55364640560655
                                                   1.52464166271477
                                                   1.61006876580606
                                                   1.52364956069532
                                                   1.81806575457738
                                                   1.48441434661028
                                                   1.74591876991852
                                                   1.74245769520403
                                                   1.68360241721359
                                                   1.4747350401555
                                                   1.70820300690374
                                                   1.63520753984176
                                                   1.54707773070829
                                                   1.71483693670782
                                                   1.82063798610205
                                                   1.5423047696417
                                                   1.36841720641699
                                                   1.51911707023119
                                                   1.47224669491031
                                                   1.53270736907412
                                                   1.44092665776395
                                                   1.47874040901983
                                                   1.67742379724035
                                                   1.43908967726316
                                                   1.52853442765087
                                                   1.61883444867739
                                                   1.68423088391742
                                                   1.85153421930177
                                                   1.50277601436284
                                                   1.64343643836763
                                                   1.74377382077206
                                                   1.44132471268945
                                                   1.57237295573363
                                                   1.54282540888818
                                                   1.57267292437882
                                                   1.4827121857253
                                                   1.48834749194092
                                                   1.32874117661961
                                                   1.44092265776372
                                                   1.79406395315794
                                                   1.70605483814925
                                                   1.43495109662625
                                                   1.34450296578704
                                                   1.47328963222689
                                                   1.79688902783481
                                                   1.57649271676158
                                                   1.79057300001031
                                                   1.88918360584204
                                                   1.52302356457986
                                                   1.99562837292139
                                                   1.52942978456656
                                                   1.67107434196289
                                                   1.53620160457489
                                                   1.96631283785436
                                                   1.74790551905562
                                                   1.65931321577715
                                                   1.6700851654338
                                                   1.44785213268332
                                                   1.65398198801089
                                                   1.52130782330193
                                                   1.48237518570537
                                                   1.45366110557588
                                                   1.59160994902815
                                                   1.54994974264284
                                                   1.50311290457884
                                                   1.43265122982357
                                                   1.43109855914351
                                                   1.52379030972325
                                                   1.55404846445386
                                                   1.59099746663899
                                                   1.63541875554053
                                                   1.67845939730159
                                                   1.4683705417399
                                                   1.44954205043032
                                                   1.59167416471822
                                                   1.80966225604119
                                                   1.76346468860323
                                                   1.74419352667924
                                                   1.56492868470515
                                                   1.64671935228726
                                                   1.83481766537199
                                                   1.66938616931403
                                                   1.47482282055285
                                                   1.52127237624101
                                                   1.56173245314358
                                                   1.61432932292077
                                                   1.37890279135083
                                                   1.74127843631076
                                                   1.54790613467884
                                                   1.71058477175047
                                                   1.61395508760452
                                                   1.66214826300364
                                                   1.52823253743694
                                                   1.83420569670835
                                                   1.42706451184612
                                                   1.60311405166927
                                                   1.57826514431738
                                                   1.88651406058613
                                                   1.39753158068781
                                                   1.68681273112893
                                                   1.55211166826089
                                                   1.50029184166691];
%%
matlabbatch{1}.spm.tools.snpm.des.Corr.cov(3).cname = 'tiv';
matlabbatch{1}.spm.tools.snpm.des.Corr.nPerm = 5000;
matlabbatch{1}.spm.tools.snpm.des.Corr.vFWHM = [0 0 0];
matlabbatch{1}.spm.tools.snpm.des.Corr.bVolm = 1;
matlabbatch{1}.spm.tools.snpm.des.Corr.ST.ST_none = 0;
matlabbatch{1}.spm.tools.snpm.des.Corr.masking.tm.tm_none = 1;
matlabbatch{1}.spm.tools.snpm.des.Corr.masking.im = 1;
matlabbatch{1}.spm.tools.snpm.des.Corr.masking.em = {'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\WTA_GM_mask.nii,1'};
matlabbatch{1}.spm.tools.snpm.des.Corr.globalc.g_omit = 1;
matlabbatch{1}.spm.tools.snpm.des.Corr.globalm.gmsca.gmsca_no = 1;
matlabbatch{1}.spm.tools.snpm.des.Corr.globalm.glonorm = 1;
matlabbatch{2}.spm.tools.snpm.cp.snpmcfg = {'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\snpm_mreg-age\SnPMcfg.mat'};
matlabbatch{3}.spm.tools.snpm.inference.SnPMmat = {'E:\Master_Thesis\Data\BIDS_AgingData\derivatives\snpm_mreg-age\SnPM.mat'};
matlabbatch{3}.spm.tools.snpm.inference.Thr.Vox.VoxSig.FWEth = 0.05;
matlabbatch{3}.spm.tools.snpm.inference.Tsign = 1;
matlabbatch{3}.spm.tools.snpm.inference.WriteFiltImg.WF_no = 0;
matlabbatch{3}.spm.tools.snpm.inference.Report = 'MIPtable';
